project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Fusión Telecom y Telefónica"
  repo-url: https://github.com/pablocerchia/fusionv2
  repo-actions: [source]
  navbar:
    background: primary
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 